"""Feature parity for the librosa-free verifier frontend.

The verifier model was trained on librosa mel + PCEN features. This box
replicates that from numpy/scipy; the golden fixtures were generated by the
training-side frontend itself (ultiwake, scripts/export_verifier_frontend.py).
If these fail after a scipy/numpy upgrade or a frontend refactor, the two
frontends have drifted and the deployed verifier is scoring features it was
never trained on.

The parity fixtures are **committed** (`tests/fixtures/`): a 3-clip subset of
ultiwake's export plus the mel filterbank. They used to live only in
`models/wakeword/`, which .gitignore blankets, so these tests had never once
run in CI or on any checkout but the author's — a silent frontend drift would
have shipped green while `verifier_mel.py` and infrastructure.md both claimed
the parity guarantee held. Three clips is the whole coverage: the STFT/mel/PCEN
path does not vary per clip, so more of them buy repetition, not coverage.

The two tests at the bottom are different: they exercise the *deployed* pair
named by the gitignored config.yaml, so they still skip off-device. Run pytest
with `-rs` (as CI does) to see that happen rather than assume it did not.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
import yaml

ROOT = Path(__file__).parent.parent
FIXTURES = Path(__file__).parent / "fixtures"
MELFB = FIXTURES / "verifier_melfb_40.npy"
GOLDEN = FIXTURES / "verifier_frontend_golden.npz"
MODELS = ROOT / "models" / "wakeword"


def _deployed_verifier() -> Path | None:
    """The stage-2 model config.yaml runs, so this covers the deployed pair
    instead of a pinned snapshot that goes stale with every promotion."""
    config = ROOT / "config.yaml"
    if not config.exists():
        return None
    wakeword = yaml.safe_load(config.read_text()).get("wakeword") or {}
    model = (wakeword.get("stage2") or {}).get("model")
    return (ROOT / model) if model else None


VERIFIER = _deployed_verifier()
DEPLOYED_MELFB = MODELS / "verifier_melfb_40.npy"


@pytest.fixture(scope="module")
def frontend():
    from openhab_voice_satellite.verifier_mel import MelPcenFrontend

    return MelPcenFrontend(MELFB)


def test_the_parity_fixtures_are_committed():
    """The guard on the guard.

    These fixtures living under models/ is what made the parity tests
    invisible for their whole existence; if they move back out, this says so
    instead of the suite quietly reporting a pass it never ran.
    """
    assert MELFB.exists() and GOLDEN.exists()


def test_features_match_the_sdk_golden_output(frontend):
    golden = np.load(GOLDEN)
    for clip, expected in zip(golden["clips"], golden["features"]):
        got = frontend(clip)
        assert got.shape == (40, 151)
        np.testing.assert_allclose(got, expected, rtol=1e-4, atol=1e-4)


def test_wrong_length_is_rejected(frontend):
    with pytest.raises(ValueError):
        frontend(np.zeros(16000, dtype=np.float32))


@pytest.mark.skipif(
    VERIFIER is None or not VERIFIER.exists(),
    reason="deployed stage-2 verifier not present (gitignored models/ + config.yaml)",
)
def test_verifier_model_scores_golden_features(frontend):
    """The deployed ONNX accepts the frontend's output and emits a probability."""
    ort = pytest.importorskip("onnxruntime")

    session = ort.InferenceSession(str(VERIFIER), providers=["CPUExecutionProvider"])
    golden = np.load(GOLDEN)
    feats = np.stack([frontend(c) for c in golden["clips"]])
    scores = session.run(None, {"features": feats})[0].flatten()
    assert scores.shape == (len(feats),)
    assert np.all((scores >= 0.0) & (scores <= 1.0))
    # golden clips are noise/tones, not the phrase — none should pass
    assert np.all(scores < 0.5)


@pytest.mark.skipif(
    VERIFIER is None or not DEPLOYED_MELFB.exists(),
    reason="deployed stage-2 verifier not present (gitignored models/ + config.yaml)",
)
def test_build_verifier_accepts_the_deployed_model():
    """The load-time input-contract check passes on the deployed pair."""
    pytest.importorskip("onnxruntime")
    from openhab_voice_satellite.config import WakewordConfig
    from openhab_voice_satellite.wakeword import BaseWakewordDetector

    session, frontend = BaseWakewordDetector._build_verifier(
        WakewordConfig(
            model="wake",
            stage2={"model": str(VERIFIER), "mel_basis": str(DEPLOYED_MELFB)},
        )
    )
    assert session is not None and frontend is not None
