"""Feature parity for the librosa-free verifier frontend.

The verifier model was trained on librosa mel + PCEN features. This box
replicates that from numpy/scipy; the golden fixtures were generated by the
training-side frontend itself (ultiwake, scripts/export_verifier_frontend.py)
and re-exported alongside every new verifier model. If these fail after a
model update, the frontends have drifted and the verifier is scoring features
it was never trained on.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
import yaml

ROOT = Path(__file__).parent.parent
MODELS = ROOT / "models" / "wakeword"
MELFB = MODELS / "verifier_melfb_40.npy"
GOLDEN = MODELS / "verifier_frontend_golden.npz"


def _deployed_verifier() -> Path | None:
    """The stage-2 model config.yaml runs, so this covers the deployed pair
    instead of a pinned snapshot that goes stale with every promotion."""
    config = ROOT / "config.yaml"
    if not config.exists():
        return None
    wakeword = yaml.safe_load(config.read_text()).get("wakeword") or {}
    model = (wakeword.get("stage2") or {}).get("model")
    return (ROOT / model) if model else None


VERIFIER = _deployed_verifier()

pytestmark = pytest.mark.skipif(
    not (MELFB.exists() and GOLDEN.exists()),
    reason="verifier frontend artifacts not present",
)


@pytest.fixture(scope="module")
def frontend():
    from openhab_voice_satellite.verifier_mel import MelPcenFrontend

    return MelPcenFrontend(MELFB)


def test_features_match_the_sdk_golden_output(frontend):
    golden = np.load(GOLDEN)
    for clip, expected in zip(golden["clips"], golden["features"]):
        got = frontend(clip)
        assert got.shape == (40, 151)
        np.testing.assert_allclose(got, expected, rtol=1e-4, atol=1e-4)


def test_wrong_length_is_rejected(frontend):
    with pytest.raises(ValueError):
        frontend(np.zeros(16000, dtype=np.float32))


@pytest.mark.skipif(
    VERIFIER is None or not VERIFIER.exists(),
    reason="configured stage-2 verifier not present",
)
def test_verifier_model_scores_golden_features(frontend):
    """The deployed ONNX accepts the frontend's output and emits a probability."""
    ort = pytest.importorskip("onnxruntime")

    session = ort.InferenceSession(str(VERIFIER), providers=["CPUExecutionProvider"])
    golden = np.load(GOLDEN)
    feats = np.stack([frontend(c) for c in golden["clips"]])
    scores = session.run(None, {"features": feats})[0].flatten()
    assert scores.shape == (len(feats),)
    assert np.all((scores >= 0.0) & (scores <= 1.0))
    # golden clips are noise/tones, not the phrase — none should pass
    assert np.all(scores < 0.5)


@pytest.mark.skipif(
    VERIFIER is None or not VERIFIER.exists(),
    reason="configured stage-2 verifier not present",
)
def test_build_verifier_accepts_the_deployed_model():
    """The load-time input-contract check passes on the deployed pair."""
    pytest.importorskip("onnxruntime")
    from openhab_voice_satellite.config import WakewordConfig
    from openhab_voice_satellite.wakeword import BaseWakewordDetector

    session, frontend = BaseWakewordDetector._build_verifier(
        WakewordConfig(
            model="wake",
            stage2={"model": str(VERIFIER), "mel_basis": str(MELFB)},
        )
    )
    assert session is not None and frontend is not None
