"""Feature parity for the librosa-free verifier frontend.

The verifier model was trained on librosa mel + PCEN features. This box
replicates that from numpy/scipy; the golden fixtures were generated by the
training-side frontend itself (ultiwake, scripts/export_verifier_frontend.py)
and re-exported alongside every new verifier model. If these fail after a
model update, the frontends have drifted and the verifier is scoring features
it was never trained on.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

MODELS = Path(__file__).parent.parent / "models" / "wakeword"
MELFB = MODELS / "verifier_melfb_40.npy"
GOLDEN = MODELS / "verifier_frontend_golden.npz"
VERIFIER = MODELS / "showdaan_listen_v6_verifier_20260817.onnx"

pytestmark = pytest.mark.skipif(
    not (MELFB.exists() and GOLDEN.exists()),
    reason="verifier frontend artifacts not present",
)


@pytest.fixture(scope="module")
def frontend():
    from openhab_voice_satellite.verifier_mel import MelPcenFrontend

    return MelPcenFrontend(MELFB)


def test_features_match_the_sdk_golden_output(frontend):
    golden = np.load(GOLDEN)
    for clip, expected in zip(golden["clips"], golden["features"]):
        got = frontend(clip)
        assert got.shape == (40, 151)
        np.testing.assert_allclose(got, expected, rtol=1e-4, atol=1e-4)


def test_wrong_length_is_rejected(frontend):
    with pytest.raises(ValueError):
        frontend(np.zeros(16000, dtype=np.float32))


@pytest.mark.skipif(not VERIFIER.exists(), reason="verifier model not present")
def test_verifier_model_scores_golden_features(frontend):
    """The shipped ONNX accepts the frontend's output and emits a probability."""
    ort = pytest.importorskip("onnxruntime")

    session = ort.InferenceSession(str(VERIFIER), providers=["CPUExecutionProvider"])
    golden = np.load(GOLDEN)
    feats = np.stack([frontend(c) for c in golden["clips"]])
    scores = session.run(None, {"features": feats})[0].flatten()
    assert scores.shape == (len(feats),)
    assert np.all((scores >= 0.0) & (scores <= 1.0))
    # golden clips are noise/tones, not the phrase — none should pass
    assert np.all(scores < 0.5)
